server:
  port: 2817

spring:
  application:
    name: caoh2-personal-website
  datasource:
    url: jdbc:mysql://localhost:3306/caoh2_app?serverTimezone=UTC&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource # \u6307\u5B9A\u4F7F\u7528Druid\u6570\u636E\u6E90
    # Druid\u8FDE\u63A5\u6C60\u76F8\u5173\u914D\u7F6E
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-while-idle: true  # \u5EFA\u8BAE\u914D\u7F6E\u4E3Atrue\uFF0C\u4E0D\u5F71\u54CD\u6027\u80FD\uFF0C\u5E76\u4E14\u4FDD\u8BC1\u5B89\u5168\u6027
      test-on-return: false
      time-between-eviction-runs-millis: 60000 # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      min-evictable-idle-time-millis: 300000 # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      filters: stat,wall,log4j2 # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true # \u5141\u8BB8HTML\u9875\u9762\u4E0A\u7684\u201CReset All\u201D\u529F\u80FD
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true # \u6162SQL\u8BB0\u5F55
          slow-sql-millis: 5000 # \u6162SQL\u8BB0\u5F55\u65F6\u95F4
        wall:
          config:
            multi-statement-allow: true # \u5141\u8BB8\u4E00\u6B21\u6267\u884C\u591A\u6761\u8BED\u53E5
            none-base-statement-allow: true # \u5141\u8BB8\u975E\u57FA\u672C\u8BED\u53E5\u7684\u5176\u4ED6\u8BED\u53E5

mybatis-plus:
  mapper-locations: classpath:**/mapper/*.xml # mapper\u6587\u4EF6\u8DEF\u5F84
  type-aliases-package: com.caoh2.app.entity # \u5B9E\u4F53\u7C7B\u8DEF\u5F84
  global-config:
    db-config:
      id-type: auto # \u4E3B\u952EID\u81EA\u589E
      table-prefix: tb_ # \u8868\u524D\u7F00
  configuration:
    map-underscore-to-camel-case: true # \u5F00\u542F\u9A7C\u5CF0\u547D\u540D\u8F6C\u6362
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # \u6253\u5370sql\u8BED\u53E5



